#!/usr/bin/env bash

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************
      __                        __     
 ____/ /  ___ _  _____ _______ / /____ 
/ __/ _ \/ -_) |/ / -_) __/ -_) __/ _ \ 
\__/_//_/\__/|___/\__/_/  \__/\__/\___/

Welcome to Vultr's One-Click Chevereto server!

To keep this server secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

In a web browser, you can view:
 * The new Chevereto site: http://$myip

On the server:
 * The default web root is located at
   /var/www/html
 * The Chevereto configuration file is located at
   /var/www/html/app/env.php
 * The MySQL root password is saved at
   /root/.mysql_password
 * Certbot is preinstalled. To configure HTTPS run:
   > certbot --apache -d example.com -d www.example.com
 * If using Cloudflare, ensure that the SSL/TLS encryption
   mode is set to "Full" or "Full (strict)" to avoid SSL handshake errors.

IMPORTANT:
 * After connecting to the server for the first time, immediately add the
   Chevereto administrator at http://$myip
 * Secure your database by running:
   > mysql_secure_installation

For help and more information, visit https://chevereto.com

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
